package $packageName$;

import org.eclipse.osgi.framework.console.CommandInterpreter;
import org.eclipse.osgi.framework.console.CommandProvider;


// referenced in component.xml
public class ServiceComponent implements CommandProvider {
	
	private DictionaryService dictionary;
	
	public void _$command$(CommandInterpreter ci) {
		String arg = ci.nextArgument();
		String word = ci.nextArgument();
		if(arg == null || word == null) {
			return;
		}
		if (arg.equalsIgnoreCase("check")) {
			if(dictionary.check(word)) {
				ci.println(word + ": exists in the dictionary");
			} else {
				ci.println(word + ": doesn't exist in the dictionary");
			}
		}
	}

	public String getHelp() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("---Generated by PDE---\n");
		buffer.append("\t$command$ check - check for the existence of a word\n");
		return buffer.toString();
	}
	
	public void setDictionary(DictionaryService d) {
		dictionary = d;
	}
	
	public void unsetDictionary(DictionaryService d) {
		dictionary = null;
	}
	
}