package $packageName$;

import org.eclipse.osgi.framework.console.CommandInterpreter;
import org.eclipse.osgi.framework.console.CommandProvider;


public class ServiceComponent implements CommandProvider {
	
	public void _$command$(CommandInterpreter ci) {
		ci.println("$message$");
	}

	public String getHelp() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("---Generated by PDE---\n");
		buffer.append("\t$command$ - do something\n");
		return buffer.toString();
	}
	
}