name: Request license-review

on:
  issue_comment:
    types: [created]

jobs:
  call-license-check:
    permissions:
      pull-requests: write
    uses: eclipse/dash-licenses/.github/workflows/mavenLicenseCheck.yml@master
    with:
      projectId: eclipse.pde
    secrets:
      gitlabAPIToken: ${{ secrets.PDE_GITLAB_API_TOKEN }}
