# This workflow will check for Maven projects if the licenses of all (transitive) dependencies are vetted.

name: License status

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  issue_comment:
    types: [created]

jobs:
  call-license-check:
    permissions:
      pull-requests: write
    uses: eclipse-dash/dash-licenses/.github/workflows/mavenLicenseCheck.yml@master
    with:
      projectId: eclipse.pde
    secrets:
      gitlabAPIToken: ${{ github.event_name == 'issue_comment' && secrets.PDE_GITLAB_API_TOKEN || '' }}
